KS-2-4 Учитывать действие баффа и выводить в консоль количество “бону…
yuriuss/KotlinSprint pull request #13
Opened 2024-08-27 22:33 UTC by yuriuss

Задача 4 к Уроку 2

В мобильной стратегии есть бафф (временное усиление какого-либо юнита или процесса), который дает +20% к добытым материалам. Было добыто 7 кристаллической и 11 железной руды без баффа – заранее известные данные, объявить и проинициализировать. 

Напиши программу, которая будет учитывать действие баффа и выводить в консоль количество “бонусных” (то есть тех материалов, которые даются “сверху” баффом). По одной строке на материал с его названием. 

Если получается нецелое число, то дробная часть должна отбрасываться.

2024-08-28 07:05 UTC, ievetrovdev requested changes

2024-08-28 07:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +const val BUFF_IN_PERCENTS = 20
20 тут не константа, потенциально процент буффа может изменится

2024-08-28 07:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val crystalOreWithBuff = crystalOre + (7 * BUFF_IN_PERCENTS) / 100
откуда тут магическое число появилось - 7?

2024-08-28 07:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    println("$crystalOreWithBuff crystal ore was mined (+$BUFF_IN_PERCENTS%)")
Прочитай внимательнее ТЗ - выводить в консоль количество “бонусных”

2024-08-28 07:08 UTC, yuriuss commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +const val BUFF_IN_PERCENTS = 20
не вопрос, поменяю на переменную.

2024-08-28 07:10 UTC, yuriuss commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val crystalOreWithBuff = crystalOre + (7 * BUFF_IN_PERCENTS) / 100
переменная для 7 имеет явное название что это, на константу не тянет. И величина эта вполне может быть изменяемая.

2024-08-28 11:07 UTC, yuriuss commented
Пофиксил. Надеюсь теперь я правильно понял.

2024-08-28 14:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val crystalOreWithBuff = crystalOre + (7 * BUFF_IN_PERCENTS) / 100
Просто у тебя 7 уже было объявлено

2024-08-28 14:10 UTC, ievetrovdev requested changes

2024-08-28 14:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buffInPercentage = .2
В ТЗ фигурирует значение 20 (процентов). Его также надо проинициализировать и только потом производить арифметические операции. Это позволит сделать более гибким и легко изменяемым, если понадобится изменить характеристики.

2024-08-28 14:31 UTC, yuriuss commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buffInPercentage = .2
Сделал переменную buffInPercentage как вариабельную, теперь она хранит заявленные 20%, но теперь не уверен что и это правильно. )

2024-08-29 14:45 UTC, ievetrovdev approved these changes
теперь все ок!

2024-08-29 14:46 UTC, merged