KS-LESSON-1-1 Добавление переменных
yuriuss/KotlinSprint pull request #4
Opened 2024-08-21 13:48 UTC by yuriuss

Пишем логику экрана приложения для интернет-магазина. Представим, что у интернет-магазина было 75 заказов. Нужно продумать релевантные названия и корректно объявить 2 переменные, которые будут содержать:
 – количество заказов,
 – текст с благодарностью за покупку (текст на твое усмотрение).

2024-08-21 16:18 UTC, ievetrovdev requested changes
Привет! отличное оформление пулл реквеста, все нейминги верные. Есть вопросики к внимательному изучению ТЗ, где сказано - "Тип переменных указывать принудительно."

Кроме того, прописаны изменяемые переменные, хотя код в данном случае в этом не нуждается. они инициализируются сразу в моменте создания и больше не перезаписываются. мы всегда изначальнопо умолчанию ставим неизменяемые переменные.

Я оставил комментарий для доработки. чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-08-21 17:15 UTC, yuriuss commented
Поправил замечания.
Но замечание "... где сказано - "Тип переменных указывать принудительно." я не нашёл такого в описании задачи.

2024-08-22 13:04 UTC, ievetrovdev commented
> Поправил замечания по поводу изменяймой/неизменяймой переменной, кол-во заказов. Но замечание "... где сказано - "Тип переменных указывать принудительно." я не нашёл такого в описании задачи.
<img width="413" alt="Снимок экрана 2024-08-22 в 16 04 04" src="https://github.com/user-attachments/assets/bc568b22-18b0-4c8e-8df7-eb5dbe69b49b">

2024-08-22 13:10 UTC, ievetrovdev approved these changes

2024-08-22 13:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    val thanksForPurchase = "Thank you for your purchase"
Давай на будущее четко следовать ТЗ, просто нужно было указать тип. сейчас аппрув. Теперь этот пулл реквест можно мержить в мастер. Перед созданием новой ветки (обязательно из мастера) не забудь сделать его Update, чтобы слитые изменения прилетели с сервера в локальный проект.

2024-08-22 14:25 UTC, yuriuss commented on src/main/kotlin/lesson_1/lesson1_task1.kt
> +    val thanksForPurchase = "Thank you for your purchase"
Да, согласен. Увидел. Спасибо.

2024-08-22 14:25 UTC, merged